### ISSUE TITLE
Inject optional Moshi and HTTP Logging Interceptor

### ISSUE THREAD

**Issue by senojl** [caseykulm/retroravelry#10]
Remove Moshi and HTTP logging interceptor from the RavelryClient for more modularity. TODO already commented in place.

**Comment by caseykulm** [comment]
We won't need to inject the interceptor if we are injecting `OkHttpClient` and `Moshi`. It will be a detail left for the user injecting those to decide if they want to add a logging interceptor.

**Comment by caseykulm** [comment]
We are calling `okHttpClient.newBuilder()` in the constructor of the `RavelryClient` which will retain any interceptors that the person injecting added.

**Comment by caseykulm** [comment]
#21
